---
kind: pipeline
name: python-2.7

platform:
  os: linux
  arch: amd64

steps:
- name: ansible2.4
  pull: always
  image: python:2.7
  commands:
  - pip install -q ansible~=2.4
  - pip install -q -r tests/requirements.txt
  - pip install -q .
  - ansible-later -c tests/config/config.ini tests/data/yaml_success.yml
  depends_on:
  - clone

- name: ansible2.5
  pull: always
  image: python:2.7
  commands:
  - pip install -q ansible~=2.5
  - pip install -q -r tests/requirements.txt
  - pip install -q .
  - ansible-later -c tests/config/config.ini tests/data/yaml_success.yml
  depends_on:
  - clone

- name: ansible2.6
  pull: always
  image: python:2.7
  commands:
  - pip install -q ansible~=2.6
  - pip install -q -r tests/requirements.txt
  - pip install -q .
  - ansible-later -c tests/config/config.ini tests/data/yaml_success.yml
  depends_on:
  - clone

- name: ansible2.7
  pull: always
  image: python:2.7
  commands:
  - pip install -q ansible~=2.7
  - pip install -q -r tests/requirements.txt
  - pip install -q .
  - ansible-later -c tests/config/config.ini tests/data/yaml_success.yml
  depends_on:
  - clone

---
kind: pipeline
name: python-3.5

platform:
  os: linux
  arch: amd64

steps:
- name: ansible2.4
  pull: always
  image: python:3.5
  commands:
  - pip install -q ansible~=2.4
  - pip install -q -r tests/requirements.txt
  - pip install -q .
  - ansible-later -c tests/config/config.ini tests/data/yaml_success.yml
  depends_on:
  - clone

- name: ansible2.5
  pull: always
  image: python:3.5
  commands:
  - pip install -q ansible~=2.5
  - pip install -q -r tests/requirements.txt
  - pip install -q .
  - ansible-later -c tests/config/config.ini tests/data/yaml_success.yml
  depends_on:
  - clone

- name: ansible2.6
  pull: always
  image: python:3.5
  commands:
  - pip install -q ansible~=2.6
  - pip install -q -r tests/requirements.txt
  - pip install -q .
  - ansible-later -c tests/config/config.ini tests/data/yaml_success.yml
  depends_on:
  - clone

- name: ansible2.7
  pull: always
  image: python:3.5
  commands:
  - pip install -q ansible~=2.7
  - pip install -q -r tests/requirements.txt
  - pip install -q .
  - ansible-later -c tests/config/config.ini tests/data/yaml_success.yml
  depends_on:
  - clone

---
kind: pipeline
name: python-3.6

platform:
  os: linux
  arch: amd64

steps:
- name: ansible2.4
  pull: always
  image: python:3.6
  commands:
  - pip install -q ansible~=2.4
  - pip install -q -r tests/requirements.txt
  - pip install -q .
  - ansible-later -c tests/config/config.ini tests/data/yaml_success.yml
  depends_on:
  - clone

- name: ansible2.5
  pull: always
  image: python:3.6
  commands:
  - pip install -q ansible~=2.5
  - pip install -q -r tests/requirements.txt
  - pip install -q .
  - ansible-later -c tests/config/config.ini tests/data/yaml_success.yml
  depends_on:
  - clone

- name: ansible2.6
  pull: always
  image: python:3.6
  commands:
  - pip install -q ansible~=2.6
  - pip install -q -r tests/requirements.txt
  - pip install -q .
  - ansible-later -c tests/config/config.ini tests/data/yaml_success.yml
  depends_on:
  - clone

- name: ansible2.7
  pull: always
  image: python:3.6
  commands:
  - pip install -q ansible~=2.7
  - pip install -q -r tests/requirements.txt
  - pip install -q .
  - ansible-later -c tests/config/config.ini tests/data/yaml_success.yml
  depends_on:
  - clone

---
kind: pipeline
name: python-3.7

platform:
  os: linux
  arch: amd64

steps:
- name: ansible2.4
  pull: always
  image: python:3.7
  commands:
  - pip install -q ansible~=2.4
  - pip install -q -r tests/requirements.txt
  - pip install -q .
  - ansible-later -c tests/config/config.ini tests/data/yaml_success.yml
  depends_on:
  - clone

- name: ansible2.5
  pull: always
  image: python:3.7
  commands:
  - pip install -q ansible~=2.5
  - pip install -q -r tests/requirements.txt
  - pip install -q .
  - ansible-later -c tests/config/config.ini tests/data/yaml_success.yml
  depends_on:
  - clone

- name: ansible2.6
  pull: always
  image: python:3.7
  commands:
  - pip install -q ansible~=2.6
  - pip install -q -r tests/requirements.txt
  - pip install -q .
  - ansible-later -c tests/config/config.ini tests/data/yaml_success.yml
  depends_on:
  - clone

- name: ansible2.7
  pull: always
  image: python:3.7
  commands:
  - pip install -q ansible~=2.7
  - pip install -q -r tests/requirements.txt
  - pip install -q .
  - ansible-later -c tests/config/config.ini tests/data/yaml_success.yml
  depends_on:
  - clone

---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: python:3.7
  commands:
  - python setup.py sdist bdist_wheel

- name: checksum
  pull: always
  image: alpine
  commands:
  - apk add --no-cache coreutils
  - "sha256sum -b dist/* > sha256sum.txt"

- name: gpg-sign
  pull: always
  image: plugins/gpgsign:1
  settings:
    detach_sign: true
    files:
    - "dist/*"
    key:
      from_secret: gpgsign_key
    passphrase:
      from_secret: gpgsign_passphrase

- name: publish-github
  pull: always
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - "dist/*"
    - sha256sum.txt
  when:
    event:
    - tag

- name: publish-pypi
  pull: always
  image: plugins/pypi
  settings:
    password:
      from_secret: pypi_password
    repository: https://upload.pypi.org/legacy/
    skip_build: true
    username:
      from_secret: pypi_username
  when:
    event:
    - tag

depends_on:
- python-2.7
- python-3.5
- python-3.6
- python-3.7

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
- name: matrix
  image: plugins/matrix
  settings:
    homeserver: https://matrix.rknet.org
    password:
      from_secret: matrix_password
    roomid: MtidqQXWWAtQcByBhH:rknet.org
    template: "Status: **{{ build.status }}**<br/> Build: [{{ repo.Owner }}/{{ repo.Name }}]({{ build.link }}) ({{ build.branch }}) by {{ build.author }}<br/> Message: {{ build.message }}"
    username:
      from_secret: matrix_username

trigger:
  status:
  - success
  - failure
  - skipped

depends_on:
- build

...
